// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgCBDRaXpCuLCyxsTokhvFuhojziLK2hU',
    appId: '1:254616501368:web:2e5b9d94e440fc9ac3c18d',
    messagingSenderId: '254616501368',
    projectId: 'app-graduation',
    authDomain: 'app-graduation.firebaseapp.com',
    storageBucket: 'app-graduation.appspot.com',
    measurementId: 'G-CB4XZME2QN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa6KkU9nD1YHV8ZesXujfO88soc9w5USo',
    appId: '1:254616501368:android:ae0add1793a83bd7c3c18d',
    messagingSenderId: '254616501368',
    projectId: 'app-graduation',
    storageBucket: 'app-graduation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjFbN12jljcTb3zcxI1lfO6Mm8vj1X9GA',
    appId: '1:254616501368:ios:0b297fea2b44a514c3c18d',
    messagingSenderId: '254616501368',
    projectId: 'app-graduation',
    storageBucket: 'app-graduation.appspot.com',
    androidClientId: '254616501368-elcrvv4ib0tfkm3qrtph1lhgu0mv0f8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.home',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjFbN12jljcTb3zcxI1lfO6Mm8vj1X9GA',
    appId: '1:254616501368:ios:b2279a49d84b77d3c3c18d',
    messagingSenderId: '254616501368',
    projectId: 'app-graduation',
    storageBucket: 'app-graduation.appspot.com',
    androidClientId: '254616501368-elcrvv4ib0tfkm3qrtph1lhgu0mv0f8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.home.RunnerTests',
  );
}
